### ISSUE TITLE
Too Many Dependencies!!

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#213]
We currently have 70 dependency packages, but after a few other prs it will be sitting at 186

**Comment by Shuzhengz** [comment]
it also takes an average 2nd gen i7 2 minutes to install acs now

**Comment by JakeRoggenbuck** [comment]
Yea, i can take out bat. That would bring it back to 70

**Comment by JakeRoggenbuck** [comment]
Here are the things we directly depend on
```toml
structopt = { version = "0.3", default-features = false }
regex = "1.5.4"
termion = "1.5.3"
nix = "0.15.0"
chrono = "0.4"
num_cpus = "1.4.0"
log = "0.4.14"
home = "0.5.3"
env_logger = "0.9.0"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
rasciigraph = "0.1.1"
```

We really need chrono for time, but maybe something else will work.
We really need nix for root check, but same, something else might work. (env!() check?)
structopt is pretty critical
log and env logger might be overkill but are super helpful
home can be taken out?
serde is needed
rasciigraph is a cool feature
