### ISSUE TITLE
Make a config file

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#83]
Make a config file for things such as
- powersave at battery percent
- performance at batter percent
- powersave at battery percent when charging
- performance at batter percent when charging
- default to governor

```toml
# This will keep the powersave on at all times when the battery is under 40, unless manually set
powersave_under = 40

# This will set powersave if the battery is charging and is under 30 to charge faster
charging_powersave_under = 30
```
